### ISSUE TITLE
Cool！ 有完整的训练的例子吗

### ISSUE THREAD

**Issue by rookie0607** [MooreThreads/MooER#1]

**Comment by lzl-mt** [comment]
We will be open-sourcing the inference code and model in the next two days, and will soon release the code for training and models trained on a larger scale dataset. Stay tuned.

**Comment by rookie0607** [comment]
非常期待！谢谢你们的开源努力，会继续关注进展。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月13日 19:05 |
| 收件人 | MooreThreads/MooER ***@***.***> |
| 抄送人 | kk ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [MooreThreads/MooER] Cool！ 有完整的训练的例子吗 (Issue #1) |

We will be open-sourcing the inference code and model in the next two days, and will soon release the code for training and models trained on a larger scale dataset. Stay tuned.

**Comment by lzl-mt** [comment]
We have released our models and inference code. Thx.
