### ISSUE TITLE
训练报错：error to parse

### ISSUE THREAD

**Issue by xinkez** [MooreThreads/MooER#16]
Hi，

我参照训练教程，生成shard格式数据后，执行train.sh，报错“error to parse”；定位发现是在speech_processor.py文件中tar_file_and_group函数报错；

我将函数tar_file_and_group中 stream = tarfile.open(fileobj=sample['stream'], mode="r|*")这行修改为stream = tarfile.open(fileobj=sample['stream'], mode="r:*")后（PS：将“|”修改为“：”），可以执行训练，没有报错。

请问是什么原因？谢谢。

**Comment by lzl-mt** [comment]
hi，我在 python 3.8.10 环境下按照教程做了打包和训练是没有问题的，error to parse的错误是训练中给出的warning吗？可能是对应某条音频的head有问题，或者没有打包完整。

**Comment by xinkez** [comment]
> hi，我在 python 3.8.10 环境下按照教程做了打包和训练是没有问题的，error to parse的错误是训练中给出的warning吗？可能是对应某条音频的head有问题，或者没有打包完整。

Hi, 感谢回复。

error to parse的错误，是在训练中给出的warning，例如：
2024-10-08 15:25:43 | WARNING | root | error to parse 908-31957-0008.wav

我确认了打包脚本中指定的wav.scp和text，确认是没问题的，并且上面提示出错的那条wav，我用librosa和torchaudio是可以正确加载的。

**Comment by lzl-mt** [comment]
> > hi，我在 python 3.8.10 环境下按照教程做了打包和训练是没有问题的，error to parse的错误是训练中给出的warning吗？可能是对应某条音频的head有问题，或者没有打包完整。
> 
> Hi, 感谢回复。
> 
> error to parse的错误，是在训练中给出的warning，例如： 2024-10-08 15:25:43 | WARNING | root | error to parse 908-31957-0008.wav
> 
> 我确认了打包脚本中指定的wav.scp和text，确认是没问题的，并且上面提示出错的那条wav，我用librosa和torchaudio是可以正确加载的。

这个warning是在Streaming的读取tar文件的时候，如果某条音频parse有问题会sikp，不影响训练。可以试下在 https://github.com/MooreThreads/MooER/blob/dd93d4016fcdd750f1438004486049fc2f19f4db/src/mooer/datasets/speech_processor.py#L172 这里加个断点看下shard里面是什么
