### ISSUE TITLE
代码疑问：每个卡都保存一次模型

### ISSUE THREAD

**Issue by bigcash** [MooreThreads/MooER#19]
我这里使用一机多卡运行模型微调，当运行代码后，发现多卡时每次保存模型时，每个卡都要保存一次模型。具体见代码src/mooer/utils/train_utils.py的line97行，if条件里没有rank==0，所以每个卡都会执行这块保存模型的代码。感觉是不是要加上这个条件，保证只在rank==0时，才会需要保存模型？

**Comment by lzl-mt** [comment]
Deepspeed训练会有pp每张卡会保存一部分的权重，实际使用的时候会有合并的步骤：https://github.com/MooreThreads/MooER/blob/7e688bea372eb90a76c09d8346701a7214caa9ed/src/mooer/utils/checpoint_io.py#L23
如果觉得占空间的话，可以加一个逻辑，merge_rank后把之前的删除，但是不建议，不然你实验中断后去resume last ckpt可能会有问题

**Comment by bigcash** [comment]
感谢解惑
