### ISSUE TITLE
inference.py cannot work with  `--wav_scp`  due to default value of `--wav_path`

### ISSUE THREAD

**Issue by edward15241** [MooreThreads/MooER#2]
In "inference.py ".
The default value of  `wav_path` is  `demo/resources/demo.wav`.   This file is  cloned from github, and always exist.
and program always detect `wav_path` first  ( in line 134  and line 156 )

```
   if args.wav_path != '' and os.path.exists(args.wav_path):
       ****
   elif args.wav_scp != '' and os.path.exists(args.wav_scp):
       **** 
```

If user input  `--wav_scp   ***  ` . the program never decode with wav_scp  because default wav_path `demo/resources/demo.wav`  is existed.

**Comment by yiliu-mt** [comment]
Thank you for the reminder. We have fixed it.
