### ISSUE TITLE
80K-v2模型发布了吗？

### ISSUE THREAD

**Issue by rookie0607** [MooreThreads/MooER#22]

**Comment by rookie0607** [comment]
@yiliu-mt

**Comment by lzl-mt** [comment]
> _No description provided._

Here's the corresponding 80k-v2 model we have open-sourced. Check it out here: 
Modelscope：https://modelscope.cn/models/MooreThreadsSpeech/MooER-MTL-80K
Huggingface：https://huggingface.co/mtspeech/MooER-MTL-80K

**Comment by rookie0607** [comment]
> > _No description provided._
> 
> Here's the corresponding 80k-v2 model we have open-sourced. Check it out here: Modelscope：https://modelscope.cn/models/MooreThreadsSpeech/MooER-MTL-80K Huggingface：https://huggingface.co/mtspeech/MooER-MTL-80K

感谢回复，我使用这个模型在speechio测试与paraformer-large差距不小。。 @lzl-mt

**Comment by lzl-mt** [comment]
> > > _No description provided._
> > 
> > 
> > Here's the corresponding 80k-v2 model we have open-sourced. Check it out here: Modelscope：https://modelscope.cn/models/MooreThreadsSpeech/MooER-MTL-80K Huggingface：https://huggingface.co/mtspeech/MooER-MTL-80K
> 
> 感谢回复，我使用这个模型在speechio测试与paraformer-large差距不小。。 @lzl-mt

我们没有在speechio上进行测试比较；不过我们在内部接近40个测试集（包括一批英文测试集）上进行了测试，平均的CER和Paraformer-large和SenseVoice是可比的。您可以使用 https://github.com/MooreThreads/MooER/blob/master/tutorial/train.md 在你的数据上Finetune，我们目前使用的数据除了开源数据集外，其余都是半监督的数据。

**Comment by rookie0607** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > Here's the corresponding 80k-v2 model we have open-sourced. Check it out here: Modelscope：https://modelscope.cn/models/MooreThreadsSpeech/MooER-MTL-80K Huggingface：https://huggingface.co/mtspeech/MooER-MTL-80K
> > 
> > 
> > 感谢回复，我使用这个模型在speechio测试与paraformer-large差距不小。。 @lzl-mt
> 
> 我们没有在speechio上进行测试比较；不过我们在内部接近40个测试集（包括一批英文测试集）上进行了测试，平均的CER和Paraformer-large和SenseVoice是可比的。您可以使用 https://github.com/MooreThreads/MooER/blob/master/tutorial/train.md 在你的数据上Finetune，我们目前使用的数据除了开源数据集外，其余都是半监督的数据。

好的，多谢。
