### ISSUE TITLE
Any instructions on getting the ouptut wav latent

### ISSUE THREAD

**Issue by wblgers** [MooreThreads/MooER#25]
Thanks for your great job!
 I want to finetune the S2S chat task, but I fail to find the code on preparing speech latent on output wav in my audio QA corpus. Can you give me some help?

**Comment by yichao-mt** [comment]
audio latents are extracted from the last layer hidden states (by teacher-forcing mode forward with the model),
```
latents = model.llm(inputs_embeds=inputs_embeds, attention_mask=attention_mask,
                                       output_hidden_states=True).hidden_states[-1]
```
