### ISSUE TITLE
mooer-omni训练的第二阶段的lable是什么？

### ISSUE THREAD

**Issue by zhiyu112223** [MooreThreads/MooER#27]
尤其是encodec response具体是怎么提取的？

**Comment by lzl-mt** [comment]
第一阶段输入为user音频，输出为回复的文本。第一阶段的Adapter训练完成后会固定；
第二阶段在第一阶段的基础上新增TTS任务，输入为回复的文本（label），输出为对应音频的encodec。对应的音频我们使用了TTS合成，encodec的label使用了一个25HZ的VQ-VAE提取得到，这一步您也可以使用开源的tokenizer。
第三阶段在第二阶段基础上，加入端到端的音频交互训练。

**Comment by zhiyu112223** [comment]
非常感谢您的回答。还有几个地方不太懂，希望您能解答。
1、第三阶段的输入<Text Promt(s2s) >指的是什么？
2、第三阶段的训练是不是除了输入user音频的adaper，还需要输入回复的文本以及回复的音频的encodec, 然后把这些输入送进llm, 产生的音频token对应的隐藏状态输入进hifigan上采样成音频？loss应该是什么？
3、第三阶段训练vocoder是不是也需要discriminator的帮助？

**Comment by lzl-mt** [comment]
1. 我们通过不同的prompt来做instruction tuning，第三阶段的<Text Promt(s2s) > 就是推理脚本里面对应的：Answer my question with speech. 
2. 第三阶段只有LLM的训练，不涉及到hifigan
3. LLM训练完成后，对应音频token的Embedding https://github.com/MooreThreads/MooER/blob/150ce3fbdb71021c4165788bf00bf3dbabb83c3b/inference_s2st.py#L249 会输入到hifigan进行训练重建回音频

最终推理的时候其实是完全端到端的，LLM的Embedding到vocoder重建回wav

**Comment by zhiyu112223** [comment]
<img width="878" alt="截屏2024-12-06 18 54 26" src="https://github.com/user-attachments/assets/e0ea1a30-027c-497b-b7d1-6a110e75b1df">
请问这段的作用对应第三阶段的哪个阶段，还是没太理解第三阶段的训练输入和输出是什么。

**Comment by lzl-mt** [comment]
> <img alt="截屏2024-12-06 18 54 26" width="878" src="https://private-user-images.githubusercontent.com/55533524/393220814-e0ea1a30-027c-497b-b7d1-6a110e75b1df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODgyNTgsIm5iZiI6MTczMzQ4Nzk1OCwicGF0aCI6Ii81NTUzMzUyNC8zOTMyMjA4MTQtZTBlYTFhMzAtMDI3Yy00OTdiLWI3ZDEtNmExMTBlNzViMWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDEyMjU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YTlmNDM4YTgwMTZiZTlhMDg4MDQ0YzkyYWYzYTcxNjc4OWRiYTQ5MDhlYzMyZTY5MGIzYTY5NWQ2YTlmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yNC6UGrNRqsC27swEziVTrKviU-m4-4S7N_nXoYHocQ"> 请问这段的作用对应第三阶段的哪个阶段，还是没太理解第三阶段的训练输入和输出是什么。

第三阶段训练输入为user的音频，输出为assistant的合成音频的encodec（离散的音频token）。上面的截图是推理阶段，和大模型训练无关，是第三阶段训练完成的LLM，将解码的encoedc对应的Embedding送到vocoder重建音频的步骤。

**Comment by zhiyu112223** [comment]
多谢您的耐心解答，请问大概什么时候能公布训练代码呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZhenlinLiang ***@***.***&gt;
发送时间: 2024年12月6日 17:10
收件人: MooreThreads/MooER ***@***.***&gt;
抄送: zhiyu112223 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MooreThreads/MooER] mooer-omni训练的第二阶段的lable是什么？ (Issue #27)





  
我们通过不同的prompt来做instruction tuning，第三阶段的<Text Promt(s2s) &gt; 就是推理脚本里面对应的：Answer my question with speech.
 
第三阶段只有LLM的训练，不涉及到hifigan
 
LLM训练完成后，对应音频token的Embedding https://github.com/MooreThreads/MooER/blob/150ce3fbdb71021c4165788bf00bf3dbabb83c3b/inference_s2st.py#L249 会输入到hifigan进行训练重建会音频
  
最终其实是完全端到端的，LLM的Embedding到vocoder重建回wav

**Comment by lzl-mt** [comment]
最近太忙了T。T，可以试着基于我们的ASR/AST的教程来训练，输出的token用开源的encodec生成下就行
