### ISSUE TITLE
speech to text

### ISSUE THREAD

**Issue by zhiyu112223** [MooreThreads/MooER#29]
你好，如果想基于您的代码改进成音频问文本答的模型，是不是直接复用asr的训练代码就行，只是把标签改成文本答复就行

**Comment by lzl-mt** [comment]
是的，参考我们的omni模型的阶段1就行。如果希望效果好，可以基于我们8wh开源的ASR模型继续训练

**Comment by lzl-mt** [comment]
instruction prompt改下就行

**Comment by zhiyu112223** [comment]
基于您的80k的asr模型微调音频问文本回答的模型，cmvn_path是不是也应该使用80k模型下的am.mvn文件。
<img width="946" alt="截屏2024-12-17 16 40 12" src="https://github.com/user-attachments/assets/f499d778-ebe7-4df6-bd7e-ce97cb10263c" />

**Comment by lzl-mt** [comment]
> 基于您的80k的asr模型微调音频问文本回答的模型，cmvn_path是不是也应该使用80k模型下的am.mvn文件。 <img alt="截屏2024-12-17 16 40 12" width="946" src="https://private-user-images.githubusercontent.com/55533524/396422682-f499d778-ebe7-4df6-bd7e-ce97cb10263c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzI5MDIsIm5iZiI6MTczNDQzMjYwMiwicGF0aCI6Ii81NTUzMzUyNC8zOTY0MjI2ODItZjQ5OWQ3NzgtZWJlNy00ZGY2LWJkN2UtY2U5N2NiMTAyNjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDEwNTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMjZkOTFmNjNkNzNiMTBkNmFiYTE5MGZlYWEyYTNkNDMzN2FjMGRhNThmOWY2ZTM1NWU4NmRjNWU1YTMyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FuEmww9UA4zyVY0t62CgMhfRxnCPUpexgNnyqKQ7O9c">

目前cmvn的文件都是一样的

**Comment by zhiyu112223** [comment]
1、请问你们的omni是否可以流式？
2、我在你们80k asr任务上微调音频问文本答的任务，使用asr_train_config，loss只能下降到1-1.4之间，请问你们的omni第一阶段在asr的configs下loss能下降到多少呢

**Comment by lzl-mt** [comment]
1. 流式指的是回复吗？可以的，但是需要改下代码，我们为了方便是直接获取到完整的Embedding后去重建音频，但是实际是可以Generate过程中就去重建音频
2. 对于omni任务，我们没有关注过loss，你可以构建一个测试集来测试对应的Bleu或者rouge分数来看效果

**Comment by lzl-mt** [comment]
> 1、请问你们的omni是否可以流式？ 2、我在你们80k asr任务上微调音频问文本答的任务，使用asr_train_config，loss只能下降到1-1.4之间，请问你们的omni第一阶段在asr的configs下loss能下降到多少呢

另外，可以这样来增加bleu和rouge的分数，构建label的时候把ASR的放前面，chat的放后面，中间用一个special token来区别；不过会慢一些

**Comment by DomoMKT** [comment]
you can find a simple yet powerful solution to convert your text into high-quality speech with extremely low latency at [www.nemesyslabs.com](https://www.nemesyslabs.com).
