### ISSUE TITLE
音频文件识别不出来

### ISSUE THREAD

**Issue by 18327850892** [MooreThreads/MooER#4]
在https://mooer-speech.mthreads.com:10077/做测试
录音正常 上传音频文件识别不出来 试了MP3 和 wav

**Comment by yiliu-mt** [comment]
hello，能否提供一下音频的具体信息，格式，通道数，采样率？我们刚刚试了几条wav是没问题的，如果方便的话也可以提供音频文件

**Comment by yiliu-mt** [comment]
具体信息查看方式是：
使用soxi：soxi <your_wav_path.wav>
或使用ffmpeg: ffmpeg -i <your_wav_path.wav>
请将相关信息贴一下，谢谢！
