### ISSUE TITLE
支持S80显卡吗？

### ISSUE THREAD

**Issue by njnuko** [MooreThreads/MooER#7]
支持S80显卡吗？

**Comment by mengc-mt** [comment]
我们看了一下S4000的后台服务，空闲时段显存占用：16915MiB，解码50s音频时显存占用：17809MiB。S80显卡显存24GB，应该可以跑的。不过目前还没有实际测试过，实际要在S80上跑起来的话需要开发一下对应的镜像。

**Comment by mengc-mt** [comment]
我们看了一下S4000的后台服务，空闲时段显存占用：16915MiB，解码50s音频时显存占用：17809MiB，S80显存16GB，目前的模型应该还不能跑。后续我们会开源训练代码，可以尝试训练更小的模型（如1.5B）跑在S80上。
