### ISSUE TITLE
出现以下报错

### ISSUE THREAD

**Issue by White-Friday** [MooreThreads/MooER#8]
Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory pretrained_models/Qwen2-7B-Instruct

模型使用的是官方的Qwen2-7B-Instruct
结构为：
README.md    
configuration.json      
merges.txt                        
model-00002-of-00004.safetensors  
model-00004-of-00004.safetensors 
tokenizer_config.json
config.json  
generation_config.json  
model-00001-of-00004.safetensors  
model-00003-of-00004.safetensors  
tokenizer.json                    
vocab.json

**Comment by White-Friday** [comment]
Traceback (most recent call last):
  File "/workspace/MooER/demo/app.py", line 80, in <module>
    this_model, this_tokenizer = mooer_model.init_model(
  File "/workspace/MooER/src/mooer/models/mooer_model.py", line 20, in init_model
    llm = setup_llm(model_config)
  File "/workspace/MooER/src/mooer/models/mooer_model.py", line 101, in setup_llm
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3260, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory pretrained_models/Qwen2-7B-Instruct.

**Comment by yiliu-mt** [comment]
It seems like it does not recognize the file in Qwen2-7B-Instruct. Can you print the output of:
```
cd pretrained_models/Qwen2-7B-Instruct
md5sum *
```

**Comment by White-Friday** [comment]
@yiliu-mt 执行 md5sum * 之后为：
b3dc906980183b2d2053fdd600258774  README.md
1e6cd0c27380f7dbb21e1ede9b6877d4  config.json
040f5895a7c8ae7cf58c622e3fcc1ba5  configuration.json
999c56b143949c3bfcb487089d08b76b  generation_config.json
e78882c2e224a75fa8180ec610bae243  merges.txt
d29bf5c5f667257e9098e3ff4eec4a02  model-00001-of-00004.safetensors
75d33ab77aba9e9bd856f3674facbd17  model-00002-of-00004.safetensors
bc941028b7343428a9eb0514eee580a3  model-00003-of-00004.safetensors
07eddec240f1d81a91ca13eb51eb7af3  model-00004-of-00004.safetensors
1c74fd33061313fafc6e2561d1ac3164  tokenizer.json
2ecf46ffaf5e727dbf5383e0e25ef73e  tokenizer_config.json
613b8e4a622c4a2c90e9e1245fc540d6  vocab.json

**Comment by yiliu-mt** [comment]
I check the md5sum's of my own. There are differences:
8d67a66d57d35dc7a907f73303486f4e  config.json
040f5895a7c8ae7cf58c622e3fcc1ba5  configuration.json
5949a57de5fd3148ac75a187c8daec7e  generation_config.json
0fb29a74e54bcc6547b79fec358aa0d1  LICENSE
e78882c2e224a75fa8180ec610bae243  merges.txt
d29bf5c5f667257e9098e3ff4eec4a02  model-00001-of-00004.safetensors
75d33ab77aba9e9bd856f3674facbd17  model-00002-of-00004.safetensors
bc941028b7343428a9eb0514eee580a3  model-00003-of-00004.safetensors
07eddec240f1d81a91ca13eb51eb7af3  model-00004-of-00004.safetensors
50ea1d5cf983231e590a7435f49320b8  model.safetensors.index.json
82953388c6fef95eadd4a5bc9c7e6b93  README.md
5c05592e1adbcf63503fadfe429fb4cc  tokenizer_config.json
1c74fd33061313fafc6e2561d1ac3164  tokenizer.json
613b8e4a622c4a2c90e9e1245fc540d6  vocab.json

Could you please double check the files which md5sum is different?

**Comment by White-Friday** [comment]
有三个文件的md5sum 是不同的，分别是tokenizer_config.json  model.safetensors.index.json config.json，我再从官方再次下载试试
