### ISSUE TITLE
Speech Recognition的test可以加入qwen-audio2的成绩对比吗

### ISSUE THREAD

**Issue by seetimee** [MooreThreads/MooER#9]

**Comment by lzl-mt** [comment]
我们内部finalize评测的时间当时qwen2-audio还没有开源模型，所以对应AST的结果也是摘录了论文中的数值，您可以在你的测试集上自己评测对比下~ 另外我们前两天已经开源了8wh训练数据训练的ASR模型，参数量和之前5kh数据的一致，新模型效果显著的优于上一版模型 https://modelscope.cn/models/MooreThreadsSpeech/MooER-MTL-80K

**Comment by lzl-mt** [comment]
另外，我们预计九月初会开源训练代码和从数据打包到推理完整的训练教程，用户也可以基于自己的数据在我们的8wh base模型上进行业务相关的微调，或者重新训练你的音频理解大模型。

**Comment by seetimee** [comment]
太棒了,我会保持关注
